/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Reminder {
  'isCancelled' : boolean,
  'isCompleted' : boolean,
  'scheduledTime' : Time,
  'name' : ReminderName,
  'creationTime' : Time,
}
export type ReminderId = bigint;
export type ReminderName = string;
export type Time = bigint;
export interface _SERVICE {
  'cancelReminder' : ActorMethod<[ReminderId], boolean>,
  'completeReminder' : ActorMethod<[ReminderId], boolean>,
  'createReminder' : ActorMethod<[ReminderName, Time], ReminderId>,
  'getActiveReminders' : ActorMethod<[], Array<Reminder>>,
  'getCompletedReminders' : ActorMethod<[], Array<Reminder>>,
  'getReminder' : ActorMethod<[ReminderId], [] | [Reminder]>,
  'getTotalReminders' : ActorMethod<[], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];