/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CountdownTimerId = IDL.Nat;
export const Time = IDL.Int;
export const CountdownTimer = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : Time,
  'duration' : Time,
  'isCompleted' : IDL.Bool,
  'endTime' : Time,
  'isPaused' : IDL.Bool,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  'completeTimer' : IDL.Func([CountdownTimerId], [], []),
  'createCountdownTimer' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [CountdownTimerId],
      [],
    ),
  'deleteTimer' : IDL.Func([CountdownTimerId], [], []),
  'getActiveTimers' : IDL.Func([], [IDL.Vec(CountdownTimer)], ['query']),
  'getAllCountdownTimers' : IDL.Func([], [IDL.Vec(CountdownTimer)], ['query']),
  'getCompletedTimers' : IDL.Func([], [IDL.Vec(CountdownTimer)], ['query']),
  'getCountdownTimer' : IDL.Func(
      [CountdownTimerId],
      [CountdownTimer],
      ['query'],
    ),
  'pauseTimer' : IDL.Func([CountdownTimerId], [], []),
  'renameCountdownTimer' : IDL.Func([IDL.Text, CountdownTimerId], [], []),
  'resumeTimer' : IDL.Func([CountdownTimerId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CountdownTimerId = IDL.Nat;
  const Time = IDL.Int;
  const CountdownTimer = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : Time,
    'duration' : Time,
    'isCompleted' : IDL.Bool,
    'endTime' : Time,
    'isPaused' : IDL.Bool,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    'completeTimer' : IDL.Func([CountdownTimerId], [], []),
    'createCountdownTimer' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [CountdownTimerId],
        [],
      ),
    'deleteTimer' : IDL.Func([CountdownTimerId], [], []),
    'getActiveTimers' : IDL.Func([], [IDL.Vec(CountdownTimer)], ['query']),
    'getAllCountdownTimers' : IDL.Func(
        [],
        [IDL.Vec(CountdownTimer)],
        ['query'],
      ),
    'getCompletedTimers' : IDL.Func([], [IDL.Vec(CountdownTimer)], ['query']),
    'getCountdownTimer' : IDL.Func(
        [CountdownTimerId],
        [CountdownTimer],
        ['query'],
      ),
    'pauseTimer' : IDL.Func([CountdownTimerId], [], []),
    'renameCountdownTimer' : IDL.Func([IDL.Text, CountdownTimerId], [], []),
    'resumeTimer' : IDL.Func([CountdownTimerId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };