/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CountdownTimer {
  'id' : bigint,
  'startTime' : Time,
  'duration' : Time,
  'isCompleted' : boolean,
  'endTime' : Time,
  'isPaused' : boolean,
  'name' : string,
}
export type CountdownTimerId = bigint;
export type Time = bigint;
export interface _SERVICE {
  'completeTimer' : ActorMethod<[CountdownTimerId], undefined>,
  'createCountdownTimer' : ActorMethod<[string, bigint], CountdownTimerId>,
  'deleteTimer' : ActorMethod<[CountdownTimerId], undefined>,
  'getActiveTimers' : ActorMethod<[], Array<CountdownTimer>>,
  'getAllCountdownTimers' : ActorMethod<[], Array<CountdownTimer>>,
  'getCompletedTimers' : ActorMethod<[], Array<CountdownTimer>>,
  'getCountdownTimer' : ActorMethod<[CountdownTimerId], CountdownTimer>,
  'pauseTimer' : ActorMethod<[CountdownTimerId], undefined>,
  'renameCountdownTimer' : ActorMethod<[string, CountdownTimerId], undefined>,
  'resumeTimer' : ActorMethod<[CountdownTimerId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];